### ISSUE TITLE
Rename packages and references to modid

### ISSUE THREAD

**Issue by Matthias1590** [RedstoneQoL/mod#2]
Not sure what to though but it might be nice to do this early so we don't have to rename as much

**Comment by RUGMJ** [comment]
I think the redstoneqol name is probably the best to go with internally and can easily  be changed if need be.

**Comment by RUGMJ** [comment]
or maybe shorter to make it easier to type, "rqol" maybe?

**Comment by Matthias1590** [comment]
it doesn't really need to be short internally, "redstonetools" seems fine

**Comment by ItsEntDev** [comment]
commit done and PR finished
