### ISSUE TITLE
Update the (one) implemented command/s to use the newer FCCv2

### ISSUE THREAD

**Issue by ItsEntDev** [RedstoneQoL/mod#23]
> FCCv2 = Fabric Client Commands V2 (net.fabricmc.fabric.api.client.command.v2)

**Comment by RUGMJ** [comment]
The command added would require the mod to be installed on the server (as it uses teleportation) meaning it cannot use the client command api although all client commands in the future should use the v2 api

**Comment by Matthias1590** [comment]
Closing this issue since no changes are needed to be made to the current code
