### ISSUE TITLE
Get glass/wool variant of block you're looking at (https://discord.com/channels/1071119659346169907/1071203190147653856)

### ISSUE THREAD

**Issue by Matthias1590** [RedstoneQoL/mod#34]
Get the glass variant of the block you're looking at if it's a wool block and get the wool variant if it's a glass block (red wool -> red stained glass and vice versa). Should be a command (/glass) without any arguments that casts a ray (no further than the player's reach) and behaves like Minecraft's middle click.

**Comment by MiranCZ** [comment]
I can do that

**Comment by Matthias1590** [comment]
Closed by #37
